sudo: required
services: 
  - docker

before_install:
  - docker build -t giucardo/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true  giucardo/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-315404249334"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $aws
  secret_access_key: "$aws_secret"



  